# SPDX-License-Identifier: Apache-2.0
"""CLI argument parsing and ``RunParams`` configuration object."""

import argparse
import importlib.util
import logging
import shutil
import sys
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace

logger = logging.getLogger(__name__)


class RunParams(SimpleNamespace):
    """Parsed runtime parameters for a spec-parser invocation."""

    # ------------------------------------------------------------------ #
    # Construction
    # ------------------------------------------------------------------ #

    def __init__(self, name: str) -> None:
        self.name = name
        self._ts: datetime = datetime.now(UTC)
        self._parse_args()
        self._check_requirements()

    # ------------------------------------------------------------------ #
    # Properties
    # ------------------------------------------------------------------ #

    @property
    def autogen_header(self) -> str:
        """One-line header string stamped into generated files."""
        return f"Automatically generated by spec-parser v{self.parser_version} on {self._ts.isoformat()}"

    @property
    def parser_version(self) -> str:
        """Version string of the running spec-parser package."""
        return sys.modules["spec_parser"].__version__  # type: ignore[attr-defined]

    @property
    def all_as_dict(self) -> dict[str, str]:
        """Template globals shared across all Jinja2 templates."""
        return {"autogen_header": self.autogen_header}

    # ------------------------------------------------------------------ #
    # Internal helpers
    # ------------------------------------------------------------------ #

    def _check_requirements(self) -> None:
        def _check_module(module_name: str, condition: str) -> None:
            if importlib.util.find_spec(module_name) is None:
                logger.error(
                    "Python module '%s' is required when %s is specified. "
                    "Make sure it's installed.",
                    module_name,
                    condition,
                )

        def _check_program(program_name: str, condition: str) -> None:
            if shutil.which(program_name) is None:
                logger.error(
                    "Program '%s' is required when %s is specified. "
                    "Make sure it's installed and present in your PATH.",
                    program_name,
                    condition,
                )

        if self.generate_jsondump:
            _check_module("jsonpickle", "JSON dump generation")
        if self.generate_mkdocs:
            _check_module("jinja2", "MkDocs generation")
        if self.generate_rdf:
            _check_module("rdflib", "RDF generation")
        if self.generate_tex:
            _check_program("pandoc", "TeX generation")
            _check_module("jinja2", "TeX generation")
        if self.generate_singlefile:
            _check_program("pandoc", "singlefile generation")
            _check_module("jinja2", "singlefile generation")

    def _parse_args(self, opts: list[str] | None = None) -> None:
        if opts is None:
            opts = sys.argv[1:]

        def _check_input_path(p: Path) -> Path:
            if not p.exists():
                raise argparse.ArgumentTypeError(f"Input directory '{p}' does not exist.")
            if not p.is_dir():
                raise argparse.ArgumentTypeError(f"Input path '{p}' is not a directory.")
            return p

        parser = argparse.ArgumentParser(
            description="Parse a specification written in Markdown and generate RDF ontology, MkDocs pages, and diagrams."
        )

        parser.add_argument("input_dir", type=str, help="Path to the input model directory.")

        parser.add_argument("-d", "--debug", action="store_true", help="Print debug information.")
        parser.add_argument("-f", "--force", action="store_true", help="Force overwrite of existing output directories.")
        parser.add_argument("-j", "--generate-jsondump", action="store_true", help="Generate a dump of the model in JSON format.")
        parser.add_argument("-J", "--output-jsondump", type=str, help="Output directory for JSON dump file.")
        parser.add_argument("-m", "--generate-mkdocs", action="store_true", help="Generate MkDocs output.")
        parser.add_argument("-M", "--output-mkdocs", type=str, help="Output directory for MkDocs files.")
        parser.add_argument("-n", "--no-output", action="store_true", help="Validate input only; produce no output.")
        parser.add_argument("-o", "--output", type=str, help="Single output directory for all output types.")
        parser.add_argument("-p", "--generate-plantuml", action="store_true", help="Generate PlantUML output.")
        parser.add_argument("-P", "--output-plantuml", type=str, help="Output directory for PlantUML files.")
        parser.add_argument("-q", "--quiet", action="store_true", help="Suppress all output below WARNING level.")
        parser.add_argument("-r", "--generate-rdf", action="store_true", help="Generate RDF output.")
        parser.add_argument("-R", "--output-rdf", type=str, help="Output directory for RDF files.")
        parser.add_argument("-t", "--generate-tex", action="store_true", help="Generate TeX output.")
        parser.add_argument("-T", "--output-tex", type=str, help="Output directory for TeX files.")
        parser.add_argument("-v", "--verbose", action="store_true", help="Print verbose information.")
        parser.add_argument("-V", "--version", action="version", version=f"%(prog)s {self.parser_version}")
        parser.add_argument("-w", "--generate-webpages", action="store_true", help="Generate web pages output.")
        parser.add_argument("-W", "--output-webpages", type=str, help="Output directory for web pages.")
        parser.add_argument("-x", "--generate-singlefile", action="store_true", help="Generate singlefile Markdown output.")
        parser.add_argument("-X", "--output-singlefile", type=str, help="Output directory for singlefile Markdown file.")

        parsed = parser.parse_args(opts)

        _gen_list = ["jsondump", "mkdocs", "plantuml", "rdf", "tex", "webpages", "singlefile"]
        _desc_list = ["JSON dump", "MkDocs", "PlantUML", "RDF", "TeX", "Web pages", "singlefile Markdown document"]

        self.quiet: bool = parsed.quiet
        self.verbose: bool = parsed.verbose
        self.debug: bool = parsed.debug

        if parsed.debug:
            logging.getLogger().setLevel(logging.DEBUG)
        elif parsed.verbose:
            logging.getLogger().setLevel(logging.INFO)

        self.input_path: Path = _check_input_path(Path(parsed.input_dir))

        if parsed.no_output:
            self.no_output: bool = True
            if any(getattr(parsed, "generate_" + g.replace("-", "_")) for g in _gen_list):
                logger.warning("Flag -n/--no-output overrides all generation flags.")
            for g in _gen_list:
                setattr(self, "generate_" + g, False)
        else:
            self.no_output = False
            attr = [getattr(parsed, "generate_" + g.replace("-", "_")) for g in _gen_list]
            if not any(attr):
                for g in _gen_list:
                    setattr(self, "generate_" + g, True)
            else:
                for g in _gen_list:
                    setattr(self, "generate_" + g, getattr(parsed, "generate_" + g.replace("-", "_")))

        if parsed.output:
            self.output_path: Path = Path(parsed.output)
            if self.output_path.exists() and not parsed.force:
                logger.error("Output directory '%s' already exists (use -f/--force to overwrite).", self.output_path)

        for desc, g in zip(_desc_list, _gen_list, strict=True):
            genflag = "generate_" + g
            if getattr(self, genflag, False):
                outdir_attr = "output_" + g
                outpath_attr = outdir_attr + "_path"
                raw = getattr(parsed, outdir_attr.replace("-", "_"), None)
                if raw:
                    setattr(self, outpath_attr, Path(raw))
                elif p := getattr(self, "output_path", None):
                    setattr(self, outpath_attr, p / g)
                else:
                    logger.error("%s was specified, but no output directory.", desc)
                if (p := getattr(self, outpath_attr, None)) and p.exists() and not parsed.force:
                    logger.error("Output directory '%s' already exists (use -f/--force to overwrite).", p)

        self.force: bool = parsed.force

    def create_output_dirs(self) -> None:
        """Create (or wipe-and-recreate when ``--force``) each enabled output directory."""
        for g in ["jsondump", "mkdocs", "plantuml", "rdf", "tex", "webpages", "singlefile"]:
            if getattr(self, "generate_" + g, False):
                p: Path = getattr(self, "output_" + g + "_path")
                if self.force and p.exists():
                    shutil.rmtree(p)
                p.mkdir(parents=True)
